apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: prod-demo-payment
  namespace: prod-demo

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: prod-demo-payment

  namespaceSelector:
    matchNames:
      - prod-demo

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
