import Link from "next/link";
import type { Evidence, Incident } from "@/types";

export function relativeTime(value:string){const seconds=Math.floor((Date.now()-new Date(value).getTime())/1000);if(seconds<60)return`${Math.max(0,seconds)}s ago`;if(seconds<3600)return`${Math.floor(seconds/60)}m ago`;if(seconds<86400)return`${Math.floor(seconds/3600)}h ago`;return`${Math.floor(seconds/86400)}d ago`}
export function SeverityBadge({value}:{value:string}){const tone=value==="SEV-1"?"badge-danger":value==="SEV-2"?"badge-warning":"badge-muted";return <span className={`badge ${tone}`}>{value}</span>}
export function StatusBadge({value}:{value:string}){const upper=value.toUpperCase();const tone=["COMPLETED","RESOLVED","APPROVED","SUCCESS"].includes(upper)?"badge-success":["FAILED","REJECTED"].includes(upper)?"badge-danger":["RUNNING","INVESTIGATING"].includes(upper)?"badge-info":"badge-muted";return <span className={`badge ${tone}`}>{value}</span>}
export function MetricCard({label,value,context,tone}:{label:string;value:string|number;context?:string;tone?:"red"|"green"|"yellow"}){return <div className="metric-card"><span className="metric-label">{label}</span><div className={`metric-value ${tone?`metric-accent-${tone}`:""}`}>{value}{context&&<span className="metric-context">{context}</span>}</div></div>}
export function IncidentTable({incidents,compact=false}:{incidents:Incident[];compact?:boolean}){return <div className="table-wrap"><table className="data-table"><thead><tr><th>Severity</th><th>Incident</th><th>Service</th><th>Status</th><th>Started</th>{!compact&&<th>Updated</th>}</tr></thead><tbody>{incidents.map(i=><tr key={i.id}><td><div className="severity-cell"><span className={`severity-bar ${i.severity==="SEV-1"?"critical":""}`}/><SeverityBadge value={i.severity}/></div></td><td><Link className="primary-cell text-link" href={`/incidents/${i.id}`}>{i.title}</Link><span className="subtext mono">{i.id.slice(0,8)}</span></td><td className="mono">{i.service}</td><td><StatusBadge value={i.status}/></td><td className="relative-time">{relativeTime(i.created_at)}</td>{!compact&&<td className="relative-time">{relativeTime(i.updated_at)}</td>}</tr>)}</tbody></table></div>}
function summarizeFinding(finding:unknown){if(typeof finding==="string")return finding;if(!finding||typeof finding!=="object")return"Tool returned structured infrastructure evidence.";const entries=Object.entries(finding as Record<string,unknown>).slice(0,3);return entries.map(([key,value])=>`${key.replaceAll("_"," ")}: ${typeof value==="object"?JSON.stringify(value):String(value)}`).join(" · ")}
export function EvidencePanel({item}:{item:Evidence}){return <article className="evidence-panel"><div className="evidence-head"><span className="tool-name">{item.tool}</span><StatusBadge value={item.status}/></div><div className="evidence-summary">{summarizeFinding(item.finding)}</div><details className="json-inspector"><summary>View raw evidence</summary><pre>{JSON.stringify(item.finding,null,2)}</pre></details></article>}
export function Timeline({steps,evidence}:{steps:string[];evidence?:Evidence[]}){const events=steps.map((step,index)=>({title:step,detail:evidence?.[index]?`${evidence[index].tool} returned ${evidence[index].status.toLowerCase()}`:"Agent planning step",meta:`Step ${String(index+1).padStart(2,"0")}`}));return <div className="timeline">{events.map((event,index)=><div className="timeline-event" key={`${event.title}-${index}`}><span className={`timeline-dot ${index===0?"info":""}`}/><h4>{event.title}</h4><p>{event.detail}</p><div className="timeline-meta">{event.meta}</div></div>)}</div>}
